Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Gaussian process posterior
def GP(X1:np.array, Y1:np.array, X2:np.array, kernel_func):
    """Computes the mean and covariance matrices of the mutlivariate gaussian of the posterior 
    $p(Y_2|X1, Y1, X2)$. It assummes mu_1 and mu_2 = 0.

    Args:
        X1 (np.array): An (m1 x n_x) matrix with m1 training x observations of n_x-dimensions.
        Y1 (np.array): An (m1 x n_y) matrix with m1 training y observations of n_y-dimensions.
        X2 (np.array): An (m2 x n_x) matrix with m2 test x observations of n_x-dimensions.
        kernel_func ([type]): Function that computes the Gram matrix for a specific kernel

    Returns:
        np.array ,np.array: mean and covariance matrices
    """

    # Kernel of the observations
    K11 = kernel_func(X1, X1)
    # Kernel of observations vs to-predict
    K12 = kernel_func(X1, X2)
    # Solve A @ X = B -> K11 @ X = K12 -> X = inv(K11) @ K12 = (K21 @ inv(K11)).T  
    K21invK11 = scipy.linalg.solve(K11, K12, assume_a='pos').T
    # Compute posterior mean
    mu2 = K21invK11 @ Y1
    
    K22 = kernel_func(X2, X2)
    # Compute the posterior covariance
    S2 = K22 - (K21invK11 @ K12)
    return mu2, S2
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-2-e41f437e78e7>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# Gaussian process posterior[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0;32mdef[0m [0mGP[0m[0;34m([0m[0mX1[0m[0;34m:[0m[0mnp[0m[0;34m.[0m[0marray[0m[0;34m,[0m [0mY1[0m[0;34m:[0m[0mnp[0m[0;34m.[0m[0marray[0m[0;34m,[0m [0mX2[0m[0;34m:[0m[0mnp[0m[0;34m.[0m[0marray[0m[0;34m,[0m [0mkernel_func[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m     """Computes the mean and covariance matrices of the mutlivariate gaussian of the posterior 
[1;32m      4[0m     [0;31m$[0m[0mp[0m[0;34m([0m[0mY_2[0m[0;34m|[0m[0mX1[0m[0;34m,[0m [0mY1[0m[0;34m,[0m [0mX2[0m[0;34m)[0m[0;31m$[0m[0;34m.[0m [0mIt[0m [0massummes[0m [0mmu_1[0m [0;32mand[0m [0mmu_2[0m [0;34m=[0m [0;36m0.[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m

[0;31mNameError[0m: name 'np' is not defined
NameError: name 'np' is not defined

